///////////////////////////////////////////////////////////////////////////////
// Untitled1Services.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_Untitled1 = 0x3F000000;
#define SRVNAME_UNTITLED1 "Untitled1"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_Untitled1CIOTest = {0x928e4a09,0x189e,0x4795,{0x9d,0xdb,0x63,0x13,0x36,0x83,0x83,0xc3}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_IOTestParameter = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _IOTestParameter
{
	ULONG data1;
	ULONG data2;
	double data3;
} IOTestParameter, *PIOTestParameter;

typedef struct _IOTestInputs
{
	ULONG Value;
	ULONG Status;
	ULONG Data;
} IOTestInputs, *PIOTestInputs;

typedef struct _IOTestOutputs
{
	ULONG Value;
	ULONG Control;
	ULONG Data;
} IOTestOutputs, *PIOTestOutputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_IOTestInputs 0
#define ADI_IOTestOutputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
