<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{062c692d-7325-45ee-af7d-e01493dac27c}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	Motor_on : BOOL;
	Motor_2_on : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="8" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>